### ISSUE TITLE
acknowledgements

### ISSUE THREAD

**Issue by orbeckst** [datreant/scipy_proceedings#3]
@datreant/coredevs – please add acknowledgements to the draft (e.g. any grants that you get paid on). Double-check with your PI if necessary. It is often very important that all grant numbers are listed because this is one way in which successes of grants are measured. 

(We can fix this in review but it's good to be complete from the start.)

**Comment by dotsdl** [comment]
@sseyler added these for everyone using the same ones from the MDAnalysis paper. We should be good.
